language: java
install: true
jdk: openjdk11
env:
  matrix:
  - TERM=dumb
before_script:
  - ./gradlew --version
script: ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls
  - curl -F 'json_file=@build/coveralls/report.json' 'https://coveralls.io/api/v1/jobs'