language: java
install: true
jdk: oraclejdk8
env:
  matrix:
  - TERM=dumb
  # list of compatible versions
  - UNDERTOW_VERSION=1.3.15.Final
  - UNDERTOW_VERSION=1.4.6.Final
before_script:
  - ./gradlew --version
script: ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls