== Response Encoders

The Encoders are used to convert response configuration data types into the outbound request content string. They are implemented as a`Function<Object,byte[]>` with the input `Object` being the configuration object being converted, and the `byte[]` is the return type.

The various configuration levels have the same method signature:

[source,groovy]
----
ServerConfig encoder(String contentType, Class objectType, Function<Object, byte[]> encoder)
----

The `contentType` is the response content type to be encoded and the `objectType` is the type of configuration object to be encoded - this allows for the same content-type to have different encoders for different configuration object types.

A simple example of an encoder would be the default "text" encoder (provided in the `io.github.cjstehno.ersatz.encdec.Encoders` class):

[source,java]
----
static Function<Object, byte[]> text(final Charset charset) {
    return obj -> (obj != null ? obj.toString() : "").getBytes(charset);
}
----

Simply stated, the response content object has `toString()` called on it and the result is then converted to bytes of the specified character set.

To use this encoder, you can configure it in a similar manner in both the server configuration block or in the response configuration block itself, which is shown below:

[source,java]
----
server.expectations(expect -> {
    expect.POST('/submit', req -> {
        req.responder(res -> {
            res.encoder(TEXT_PLAIN, String.class, Encoders.text(UTF_8));
            req.body("This is a string response!", TEXT_PLAIN);
        });
    });
});
----

TIP: As a design decision, no encoders are defined and registered on the server by default. If you need one, you need to register it. The only caveat to this is that if no encoder is specified, an attempt will be made to convert the body content to a byte array, if such a method is available.

=== Provided Encoders

The API provides a handful of commonly used encoders. These are defined in the `io.github.cjstehno.ersatz.encdec.Encoders` class, and described below:

* **Text.** Encodes the object as a `String` of text, with optional character set specification.
* **Content.** Loads the content at the specified destination and returns it as a byte array. The content destination may be specified as an `InputStream`, `String`, `Path`, `File`, `URI`, or `URL`.
* **Binary Base64.** Encodes a byte array, InputStream or other object with a "getBytes()" method into a base-64 string.
* **Multipart.** Encodes a `MultipartResponseContent` object to its multipart string representation.

=== JSON Encoders

As of 3.0.0 the built-in JSON Encoder was removed (to avoid dependency lock-in). Below are provided some simple/common implementations of them for use in your code:

==== Groovy

An encoder (serializer) implemented with the Groovy `JsonOutput` could be implemented as:

public static final Function<Object, byte[]> json = obj -> (obj != null ? toJson(obj) : "{}").getBytes(UTF_8);

[source,groovy]
----
encoder(ContentType.APPLICATION_JSON, MyType){ obj ->
    JsonOutput.toJson(obj).getBytes(UTF_8)
}
----

TIP: If you are using the Groovy extension library, this encoder is available as the `JsonEncoder` class.

==== Jackson

An encoder (serializer) implemented using the Jackson JSON library could be implemented as:

[source,java]
----
encoder(ContentType.APPLICATION_JSON, MyType.class, obj -> {
    return new ObjectMapper().writeValueAsBytes(obj);
});
----