= Ersatz Server Tutorial
Christopher J. Stehno
v3.2.0, May 2023
:toc: left
:toclevels: 4

== Introduction

The Ersatz server library is a useful tool for testing a REST client library using simple expectations based on real server request/response interactions, however, it has a lot of little features and bits of functionality that may be lost or overlooked when you scan through the documentation. So, I figured it would be useful to have a walk-through tutorial to try and showcase and explain all the little bits in a more hands-on environment.


we will walk through writing and testign a client for a hypothetical REST API,
DESCRIBE and link to DOCS.
While this is a realistic example as far as testing goes, the REST interface itself will be kept somewhat minimal so as not to distract us from the real goal here, which is to learn how to use the features of Ersatz.


> This is not meant to be a tutorial on how to write a RESTful API.


---

define project and REST interface
setup project (client and test areas) - ersatz and test-things
work through each test and client endpoint
refactor as needed.

---

We'll start with the token request...