= Ersatz Server User Guide
Christopher J. Stehno
v4.0.1, February 2024
:toc: left
:toclevels: 4

== Introduction

The Ersatz Server is an HTTP client testing tool, which allows for request and response expectations to be configured in a flexible manner. The expectations will respond to each request in a configured manner allowing tests with different responses and/or error conditions without having to write a lot of boilerplate code.

The "mock" server is not really a mock at all, it is an embedded Undertow HTTP server which registers the configured expectations as routes and then responds according to the configured expectation behavior. This approach may seem overly heavy; however, testing an HTTP client can involve a lot of internal state and interactions that the developer is generally unaware of (and should be) - trying to mock those interactions with a pure mocking framework will get out of hand very quickly, and Undertow starts up very quickly.

Ersatz provides a balance of mock-like expectation behavior with a real HTTP interface and all of the underlying interactions in place. This allows for rich unit testing, which is what you were trying to do in the first place.

Ersatz is written in Java 15 due to its use of the modern functional libraries; however, there is an extension library (ersatz-groovy) which provides a Groovy DSL and extensions to the base library.

Lastly, Ersatz is developed with testing in mind. It does not favor any specific testing framework, but it does work well with both the JUnit and Spock frameworks.

NOTE: The code examples throughout this document are written with either Java or Groovy code. Please note that all features are available to both languages and will be configured in a similar manner in each.

include::whats_new.adoc[]

include::getting_started.adoc[]

include::junit_extension.adoc[]

include::lifecycle.adoc[]

include::configuration.adoc[]

include::request_decoders.adoc[]

include::response_encoders.adoc[]

include::requirements.adoc[]

include::expectations.adoc[]

include::web_sockets.adoc[]

== Shadow Jar

The embedded version of Undertow used by Ersatz has caused issues with some server frameworks which also use Undertow (e.g. Grails, and Spring-boot).

If you run into errors using the standard jar distribution, please try using the `safe` distribution, which is a shadowed jar that includes the Undertow library and many of the other dependencies repackaged in the jar. You can use this version in the manner described below for your build system.

NOTE: There are examples of various usage configurations in the https://github.com/cjstehno/ersatz-usage-tests[Ersatz Usage Tests] project.

=== Gradle

A Gradle `gradle.build` file would have the following defined in the `dependencies` block:

[source,groovy]
----
testImplementation('io.github.cjstehno.ersatz:ersatz:4.0.1:safe'){
    exclude group:'io.undertow', module:'undertow-core'
    exclude group:'javax.servlet', module:'javax.servlet-api'
    exclude group:'commons-fileupload', module:'commons-fileupload'
}

// or for the Groovy DSL
testImplementation('io.github.cjstehno.ersatz:ersatz-groovy:4.0.1:safe'){
    exclude group:'io.undertow', module:'undertow-core'
    exclude group:'javax.servlet', module:'javax.servlet-api'
    exclude group:'commons-fileupload', module:'commons-fileupload'
}
testImplementation 'org.codehaus.groovy:groovy:3.0.9'
testImplementation 'javax.activation:activation:1.1.1'
testImplementation 'org.hamcrest:hamcrest-library:2.2'
----

The inclusions and exclusions are required to truly isolate and configure the artifact, due to some odd maven publishing requirements.

=== Maven

For a Maven `pom.xml` entry, this would be:

[source,xml]
----
<dependency>
    <groupId>io.github.cjstehno.ersatz</groupId>
    <artifactId>ersatz</artifactId>
    <classifier>safe</classifier>
    <version>4.0.1</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>io.undertow</groupId>
            <artifactId>undertow-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </exclusion>
        <exclusion>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<!-- or, for the Groovy DSL -->
<dependency>
    <groupId>io.github.cjstehno.ersatz</groupId>
    <artifactId>ersatz-groovy</artifactId>
    <classifier>safe</classifier>
    <version>4.0.1</version>
    <type>jar</type>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>io.undertow</groupId>
            <artifactId>undertow-core</artifactId>
        </exclusion>
        <exclusion>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </exclusion>
        <exclusion>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy</artifactId>
    <version>3.0.9</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-library</artifactId>
    <version>2.2</version>
    <scope>test</scope>
</dependency>
----

The inclusions and exclusions are required to truly isolate and configure the artifact, due to some odd maven publishing requirements.

include::usage_examples.adoc[]

== Appendices

=== A. Development Philosophy

As this project starts its seventh year (started in December 2016) it's doing well, and it is stable, but I have less time to devote to it. I figured it would be a good time to outline my general development philosophy/strategy for the project as it moves forward.

The primary goal of the 3.x release was increased simplicity and ease of development. This is why I removed some of the more niche features in favor of keeping it more maintainable. I also removed some automated development tools (e.g. Coveralls and Travis). There is some maintenance effort involved in keeping them current, and I am a one-developer team - the information provided by these tools can easily be discovered by building the project (and will be published with the releases).

Being that this is a project used in writing unit tests, I don't generally feel the need for strict backwards compatability as long as there is a simple upgrade path. That being said, if some change causes a major problem, I am not against cutting a new release with changes that make the transition easier.

The audience for this project is very small and there are very few bugs and feature requests, so if that continues, I will plan on putting out a new release once a year to keep up with current JDK and dependency versions.

=== B. License

This project is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 License].

----
Copyright (C) 2023 Christopher J. Stehno

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
----
